version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    groups:
      actions-minor-patch:
        update-types:
          - minor
          - patch
    schedule:
      interval: monthly
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: monthly
